### PR TITLE
completed css-brochure-form - Fredrick Rana

### PR DESCRIPTION
**Pull request by fredrickrana**
Screen Shot 2022-05-12 at 3 26 29 AM

### CODE REVIEW

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Fredrick, your form is too wide as compared to the example, please revise and submit a new screenshot with your revision

**Comment by fredrickrana** [comment]
completed css-brochure-form, adjusted the width of the input and select to match example

**Comment by fredrickrana** [comment]
Screen Shot 2022-05-13 at 3 44 10 PM

**Review by codingcodymiller — APPROVED** [review]
Nice work!

**Pull request merged**
