### PR TITLE
completed css-two-column-layout - Fredrick Rana

### PR DESCRIPTION
**Pull request by fredrickrana**
Screen Shot 2022-05-15 at 5 53 04 AM

### CODE REVIEW

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Fredrick, please try to do this using proper layout class structure as described in `css-layout-classes`. Also, please avoid using `float`. It's not a bad tool, but it can be easily used as a band-aid fix where a better approach is available.

**Comment by fredrickrana** [comment]
Screen Shot 2022-05-24 at 3 49 45 AM

**Review by codingcodymiller — CHANGES_REQUESTED** [review]

**Comment by fredrickrana** [comment]
Screen Shot 2022-05-29 at 4 20 53 PM
Revised names of classes to be better for reusability. Changed column-box to row and edited original column names to match the size of column classes.

**Review by codingcodymiller — APPROVED** [review]
Nice work!

**Pull request merged**
